### ISSUE TITLE
is 32bit windows os supported? if not, please provide support

### ISSUE THREAD

**Issue by githubfanster** [rivo/tview#17]
tview works well in my 64bit windows 10 environment but we still have 32bit windows 7.x and 8.x machines.

i tried downloading (go get ...)   in a 32bit windows 8.x machine, as well as creating a 32bit exe from my 64bit machine, and compilation step both failed with integer overflow error ...

F:\gowork\src\tviewdemo\presentation>go build tviewdemo\presentation
# github.com/rivo/tview
..\..\github.com\rivo\tview\inputfield.go:157:15: constant 9223372036854775807 overflows int
..\..\github.com\rivo\tview\textview.go:452:9: constant 9223372036854775807 overflows int
..\..\github.com\rivo\tview\util.go:131:7: constant 9223372036854775807 overflows int

**Comment by rivo** [comment]
I fixed the offending code but haven't tried it on a 32bit machine yet. Could you please let me know if it works there now?

**Comment by githubfanster** [comment]
i did a go get -u github.com/rivo/tview, set GOARCH environment to 386, then built the presentation demo and the build / compilation succeeded. i was able to run the presentation demo, but as i change from one slide to another, the highlighting in the bottom row "menu" seemed a little off. if i am currently in "menuitem" 5, the menuitem label is obscured instead of highlighted properly (compared to the 64bit exe i built from the download from a few days ago)

so thanks so much for making it possible to compile to 32bit exe!!

**Comment by githubfanster** [comment]
i did a go get -u github.com/rivo/tview, set GOARCH environment to 386,
then built the presentation demo and the build / compilation succeeded. i
was able to run the presentation demo, but as i change from one slide to
another, the highlighting in the bottom row "menu" seemed a little off. if
i am currently in "menuitem" 5, the menuitem label is obscured instead of
highlighted properly (compared to the 64bit exe i built from the download
from a few days ago)

so thanks so much for making it possible to compile to 32bit exe!!

**Comment by rivo** [comment]
I tried to run this on an old WinXP machine that I still had lying around. Couldn't get it to run. I think `tcell` doesn't support this (or I don't know how to configure WinXP for it). So unfortunately, I can't reproduce what you're seeing. I don't have any other 32bit machine.

I know one shouldn't use WinXP anymore but it would still be fun to be able to write stuff like this for old platforms. If you have an idea how to make it work, let me know.

**Comment by githubfanster** [comment]
i tested tview on a windows 8.1 machine and it worked. i didn't pay
attention to the slight highlighting problem i reported but when i get back
to that machine at work i'll do so.
i have to see if we still have any xp machines around.
